#!/usr/bin/env ruby

# to install, add the following line to your .bash_profile or .bashrc
# complete -C path/to/sake_completion -o default sake

# Sake completion will return matching sake tasks given typed text. This way
# you can auto-complete tasks as you are typing them by hitting [tab] or [tab][tab]
# This also caches the sake tasks for optimium speed
class SakeCompletion
  CACHE_FILE_NAME = '/home/badboy/.sake_tasks~'
  
  def initialize(command)
    @command = command
  end
  
  def matches
    exit 0 if sakefile.nil?
    matching_tasks
  end
  
  private
  
  def typed
    @command || ''
  end
  
  def typed_before_colon
    typed[/.+\:/] || ''
  end
  
  def matching_tasks
    all_tasks.select do |task|
      task[0, typed.length] == typed
    end
  end
  
  def all_tasks
    cache_current? ? tasks_from_cache : generate_tasks
  end
  
  def cache_current?
    File.exist?(cache_file) && File.mtime(cache_file) >= File.mtime(sakefile)
  end
  
  def sakefile
    ['/home/badboy/.sake'].detect do |file|
      File.file? file
    end
  end
  
  def cache_file
    CACHE_FILE_NAME
  end
  
  def tasks_from_cache
    IO.read(cache_file).split
  end
  
  def generate_tasks
    tasks = `sake -T`.split("\n").collect {|line| line.split[1]}
    File.open(cache_file, 'w') { |f| f.write tasks.join("\n") }
    tasks
  end
end

puts SakeCompletion.new(ARGV.join).matches
exit 0
